# Generated by Django 4.0.4 on 2022-06-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='price',
            new_name='new_price',
        ),
    ]
