# Generated by Django 4.0.4 on 2022-06-13 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('label_sale', models.CharField(blank=True, max_length=50, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('category', models.CharField(blank=True, choices=[('laptops', 'laptops'), ('smartphones', 'smartphones'), ('lcd', 'lcd'), ('cameras', 'cameras'), ('accessories', 'accessories')], max_length=100, null=True)),
                ('productimage0', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
                ('productimage1', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
                ('productimage2', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
                ('productimage3', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
                ('color', models.CharField(blank=True, choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue'), ('black', 'black'), ('selver', 'selver'), ('red', 'red')], max_length=100, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
