# Generated by Django 4.0.4 on 2022-06-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_new_price_alter_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('labtops', 'labtops'), ('smartphones', 'smartphones'), ('lcd', 'lcd'), ('cameras', 'cameras'), ('accessories', 'accessories')], max_length=100, null=True),
        ),
    ]
