# Generated by Django 4.0.4 on 2022-06-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('toshiba', 'toshiba'), ('samsung', 'samsung'), ('lg', 'lg'), ('oppo', 'oppo'), ('hawui', 'hawui'), ('tornado', 'tornado')], max_length=50, null=True),
        ),
    ]
